export const GET_MOVIES = 'GET_MOVIES';
export const ADD_FAVORITE_ITEM = 'ADD_FAVORITE_ITEM';
export const REMOVE_FAVORITE_ITEM = 'REMOVE_FAVORITE_ITEM';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
